name: Use Thumbnail

on:
  push:
    branches: [ main ]

jobs:
  thumbnail:
    uses: ficilabs/automation-thumbnail/.github/workflows/thumbnail.yml@main
    with:
      url: "https://talkled-ficilabs.vercel.app"
